### ISSUE TITLE
Upstream base-linux

### ISSUE THREAD

**Issue by jklmnn** [jklmnn/base-linux-hw#10]
When bringing the changes for base-linux upstream I would move the required parts of this repository to genodes base-linux. I don't think that it is necessary to include an additional repo. Currently this would only be src/lib/initramfs. Anything else is only for testing/documentation purposes but not required to build base-linux. What are your thoughts on that @senier?

**Comment by senier** [comment]
Yep, a dedicated base-linux-hw repo is unnecessary. Integrate it into regular base-linux.
