### ISSUE TITLE
Change repository dedication

### ISSUE THREAD

**Issue by jklmnn** [jklmnn/base-linux-hw#2]
@senier 
Since we don't use this repository as core anymore for Genode on Linux I'd say that we use it for any utilities we create (beside the documentation). My first step would be moving the init binary from [jklmnn/initramfs](https://github.com/jklmnn/initramfs) to this repo and build it from source (instead providing the binary itself).
The not yet created port for building the Linux kernel might also reside here.
What's your opinion about this?

**Comment by senier** [comment]
Yes, that sounds reasonable.
