### ISSUE TITLE
Save log and print later

### ISSUE THREAD

**Issue by jklmnn** [jklmnn/base-linux-hw#4]
I created a run file to safe the log in a vfs and log it later (when the terminal is up). It breaks down to the following services:
```
<LOG>-->[fs_log]--<File_system>-->[vfs]--<File_system>-->[fs_rom]--<ROM>-->[rom_logger]--<LOG>
``` 
Currently it seems that `fs_log` logs to the FS and `rom_logger` requests the correct file through `fs_rom` (otherwise `fs_rom` prints a lookup failed error) but the ROM returned is invalid (according to `rom_logger`).
cc @senier 
see https://github.com/jklmnn/base-linux-hw/commit/afe54d3a264832a8f345f583ef011d833f4859c2

**Comment by jklmnn** [comment]
Fixed by https://github.com/genodelabs/genode/issues/2207.

**Comment by senier** [comment]
Cheater ;-)
